# This file allows testing using travis CI servers to use it you'll need to
# create an account in travis.org and enable your addon there. 
# by default only linux 64bit and osx are tested. Other platforms can be enabled
# by uncommenting the corresponding sections.
#
# If any extra install is needed to use the addon it can be included in the corresponding
# install script in:
#
# scripts/ci/$TARGET/install.sh
#


language: c++
compiler: gcc
sudo: true
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

# Linux 64bit
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - gdb

# OSX
  - os: osx
    osx_image: xcode8
    compiler: clang
    env: TARGET="osx"

# Linux ARM6: Uncomment following lines to enable 
#  - os: linux
#    sudo: required
#    dist: trusty
#    env: TARGET="linuxarmv6"


# Linux ARM7: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="linuxarmv7"
#    cache:
#      directories:
#        - ~/rpi2_toolchain


# Emscripten: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="emscripten"
#    addons:
#      apt:
#        sources:
#          - ubuntu-toolchain-r-test
#        packages:
#          - libstdc++6


# iOS: Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="ios"


# tvOS: Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="tvos"


# Android armv7: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="armv7"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


# Android x86: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="x86"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - compiler: gcc

install:
  - cd ~
  - git clone --depth=1 https://github.com/openframeworks/openFrameworks
  - cd openFrameworks
  - if [ "$TARGET" == "android" ] || [ "$TARGET" == "linux" ] || [ "$TARGET" == "linuxarmv6" ] || [ "$TARGET" == "linuxarmv7" ] || [ "$TARGET" == "docs" ] || [ "$TARGET" == "osx" ] || [ "$TARGET" == "emscripten" ]; then
        scripts/ci/$TARGET/install.sh;
    fi
  - if [ "$TARGET" == "linux" ]; then
        scripts/linux/download_libs.sh -a 64;
    elif [ "$TARGET" == "linuxarmv6" ]; then
        scripts/linux/download_libs.sh -a armv6l;
    elif [ "$TARGET" == "linuxarmv7" ]; then
        scripts/linux/download_libs.sh -a armv7l;
    elif [ "$TARGET" == "tvos" ]; then
        scripts/ios/download_libs.sh;
    else
        scripts/$TARGET/download_libs.sh;
    fi
  - cd $TRAVIS_BUILD_DIR
  - if [ -f scripts/ci/install.sh ]; then
        scripts/ci/install.sh;
    fi
  - if [ -f scripts/ci/$TARGET/install.sh ]; then
        scripts/ci/$TARGET/install.sh;
    fi


script:
  - cd ~
  - mv $TRAVIS_BUILD_DIR ~/openFrameworks/addons/
  - cd ~/openFrameworks/addons/$(basename $TRAVIS_BUILD_DIR)
  - for example in example*; do
        cp ~/openFrameworks/scripts/templates/$TARGET/Makefile $example/;
        cp ~/openFrameworks/scripts/templates/$TARGET/config.make $example/;
        cd $example;
        if [ "$TARGET" == "android" ]; then
            echo "ABIS_TO_COMPILE_DEBUG = $OPT" >> config.make;
            make Debug PLATFORM_OS=Android;
        else
            make Debug;
        fi
    done

git:
  depth: 10
